Update ss_go_debian
번역

diff --git a/service/ss_go_debian b/service/ss_go_debian
--- a/service/ss_go_debian
+++ b/service/ss_go_debian
@@ -17,8 +17,8 @@ CONF="/usr/local/shadowsocks-go/shadowsocks-go.conf"
 LOG="/usr/local/shadowsocks-go/shadowsocks-go.log"
 
 Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Green_background_prefix="\033[42;37m" && Red_background_prefix="\033[41;37m" && Font_color_suffix="\033[0m"
-Info="${Green_font_prefix}[信息]${Font_color_suffix}"
-Error="${Red_font_prefix}[错误]${Font_color_suffix}"
+Info="${Green_font_prefix}[정보]${Font_color_suffix}"
+Error="${Red_font_prefix}[오류]${Font_color_suffix}"
 RETVAL=0
 
 check_running(){
@@ -30,7 +30,7 @@ check_running(){
 	fi
 }
 read_config(){
-	[[ ! -e ${CONF} ]] && echo -e "${Error} $NAME 配置文件不存在 !" && exit 1
+	[[ ! -e ${CONF} ]] && echo -e "${Error} $NAME 설정 파일 없음 !" && exit 1
 	port=$(cat ${CONF}|grep 'PORT = '|awk -F 'PORT = ' '{print $NF}')
 	password=$(cat ${CONF}|grep 'PASSWORD = '|awk -F 'PASSWORD = ' '{print $NF}')
 	cipher=$(cat ${CONF}|grep 'CIPHER = '|awk -F 'CIPHER = ' '{print $NF}')
@@ -44,19 +44,19 @@ read_config(){
 do_start(){
 	check_running
 	if [[ $? -eq 0 ]]; then
-		echo -e "${Info} $NAME (PID ${PID}) 正在运行..." && exit 0
+		echo -e "${Info} $NAME (PID ${PID}) 실행중..." && exit 0
 	else
 		read_config
 		cd ${FOLDER}
-		echo -e "${Info} $NAME 启动中..."
+		echo -e "${Info} $NAME 시작 중..."
 		ulimit -n 51200
 		nohup ./shadowsocks-go -s ":${port}" -cipher "${cipher}" -password "${password}" "${verbose}" >> "${LOG}" 2>&1 &
 		sleep 2s
 		check_running
 		if [[ $? -eq 0 ]]; then
-			echo -e "${Info} $NAME 启动成功 !"
+			echo -e "${Info} $NAME 실행 성공 !"
 		else
-			echo -e "${Error} $NAME 启动失败 !请查看日志文件检查问题所在。"
+			echo -e "${Error} $NAME 실행 실패 ! 이력파일을 확인하여 문제점을 확인하세요."
 		fi
 	fi
 }
@@ -66,21 +66,21 @@ do_stop(){
 		kill -9 ${PID}
 		RETVAL=$?
 		if [[ $RETVAL -eq 0 ]]; then
-			echo -e "${Info} $NAME 停止成功 !"
+			echo -e "${Info} $NAME 중지 성공 !"
 		else
-			echo -e "${Error} $NAME 停止失败 !"
+			echo -e "${Error} $NAME 중지 실패 !"
 		fi
 	else
-		echo -e "${Info} $NAME 未运行"
+		echo -e "${Info} $NAME 미실행"
 		RETVAL=1
 	fi
 }
 do_status(){
 	check_running
 	if [[ $? -eq 0 ]]; then
-		echo -e "${Info} $NAME (PID ${PID}) 正在运行..."
+		echo -e "${Info} $NAME (PID ${PID}) 실행중..."
 	else
-		echo -e "${Info} $NAME 未运行 !"
+		echo -e "${Info} $NAME 미실행 !"
 		RETVAL=1
 	fi
 }
@@ -93,7 +93,7 @@ case "$1" in
 	do_$1
 	;;
 	*)
-	echo "使用方法: $0 { start | stop | restart | status }"
+	echo "사용방법: $0 { start | stop | restart | status }"
 	RETVAL=1
 	;;
 esac
